# Generated by Django 4.0.2 on 2022-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=7)),
                ('office', models.CharField(max_length=500)),
                ('program', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('year_to_date', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
        ),
    ]
